/* import { createElement } from '@lwc/engine-dom';
import Demo_OpportunityOperativas from 'c/demo_OpportunityOperativas';

describe('c-demo-opportunity-operativas', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-demo-opportunity-operativas', {
            is: Demo_OpportunityOperativas
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
}); */